In [2]:
import numpy as np

# Check NumPy version
print(f'NumPy version: {np.__version__}')

NumPy version: 2.2.4


# Linear Algebra with NumPy

This notebook explores fundamental linear algebra concepts using NumPy, covering:
- Vectors and matrices
- Basic matrix operations
- Matrix multiplication
- Special matrices
- Linear algebra operations

## Vectors

Let's start by creating and manipulating vectors using NumPy arrays.

In [3]:
# Create vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f'Vector 1: {v1}')
print(f'Vector 2: {v2}')

# Vector operations
print(f'\nAddition: {v1 + v2}')
print(f'Dot product: {np.dot(v1, v2)}')
print(f'Vector magnitude (v1): {np.linalg.norm(v1):.2f}')

Vector 1: [1 2 3]
Vector 2: [4 5 6]

Addition: [5 7 9]
Dot product: 32
Vector magnitude (v1): 3.74


In [4]:
# Custom vector-vector multiplication

def vec_vec_mul(a, b):
    #assert a.shape == b.shape
    sum = 0
    for ai, bi in zip(a,b):
        sum += ai * bi
    return sum

# Custom matrix-vector multiplication

def mul_vec_multiplication(A, b):
    assert A.shape[1] == b.shape[0] 
    out = []
    for ai in A: 
        #row vectors
        out.append(vec_vec_mul(ai, b))
    return np.array(out)



In [5]:
v1.shape[0]

3

In [6]:
# test dot product

print(vec_vec_mul(v1, v2))

32


In [7]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

v = np.array([3,4,5,1])

print(mul_vec_multiplication(U, v))

[53 18 24]


In [8]:
#some helper functions

def get_ith_colvec(Matrix, i):
    return Matrix[:, i]

def get_ith_rowvec(Matrix, i):
    return Matrix[i, :]

## A harder way
def mat_mat_multiplication(A, B):
    assert A.shape[1] == B.shape[0]
    main_mat = []
    for i in range(len(A)):
        sub_array = []
        row_vec = get_ith_rowvec(A, i)
        for j in range(len(B)):
            col_vec = get_ith_rowvec(B, j)
            sub_array.append(vec_vec_mul(row_vec, col_vec))
        main_mat.append(sub_array)

    return np.array(main_mat)

## more elegant




In [9]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2,1, 0]
])
mat_mat_multiplication(U, V)

array([[16. ,  7. , 13. ,  8. ],
       [ 5. ,  2. ,  5. ,  4. ],
       [ 8. ,  2.5,  4. ,  7. ]])

In [10]:
# Identity Matrix

I  = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

inv = np.linalg.inv(V)

print(inv)

[[ 1.         -2.          0.        ]
 [ 0.         -0.66666667  0.66666667]
 [ 0.          1.33333333 -0.33333333]]
